image: maven:3-jdk-11

stages:
  - build
  - package

.only-main:
  only:
    - main

build:
  extends: .only-main
  script: "mvn clean install"
package:
  extends: .only-main
  script: "mvn package -T 1C -B -f PizzaToGo/pom.xml"
