image: maven:3-jdk-11
variables:
  REGISTRY_URL: gitlab.rlp.net/hettel/ws2023_team_c
  IMAGE_PREFIX: WS2023_Team_C
stages:
  - build
  - package
  - build_push

.only-main:
  only:
    - main

build:
  stage: build
  script: "mvn clean install -f PizzaToGo/pom.xml"
package:
  stage: package
  script: "mvn package -f PizzaToGo/pom.xml"
